config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update, :destroy] do
    resources :memos, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :prices, only: [:index, :new, :create, :edit, :update, :destroy]
    namespace :api do
      resources :prices, only: :index, defaults: { format: 'json' }
    end
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :prices, dependent: :destroy
  has_many :memos, dependent: :destroy
  
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :group

  validates :text, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :group

  validates :number, presence: true
  validates :name, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  mount_uploader :image, ImageUploader
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id]
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/api/prices_controller.rb
class Api::PricesController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @prices = Price.where(['name LIKE ?', "%#{params[:keyword]}%"]).where(group_id: current_user.groups.ids).limit(8)
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを編集しました"
    else
      render :edit
    end
  end

  def destroy
    group = Group.find(params[:id])
    if group.destroy
      redirect_to root_path, notice: "削除しました"
    else
      flash.now[:alert] = "通信エラーです"
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [] )
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_group
  
  def index
    @memos = @group.memos
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = @group.memos.new(memo_params)
    if @memo.save
      redirect_to group_memos_path, notice: "メモを作成しました"
    else
      flash.now[:alert] = "内容を入力してください"
      render :new
    end
  end

  def destroy
    memo = Memo.find(params[:id])
    if memo.destroy
      redirect_to group_memos_path, notice: "削除しました"
    else
      flash.now[:alert] = "通信エラーです"
      render :index 
    end
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    memo = Memo.find(params[:id])
    if memo.update(memo_params)
      redirect_to group_memos_path, notice: "更新しました"
    else
      flash.now[:alert] = "通信エラーです"
      render :index 
    end
  end
  
  private

  def memo_params
    params.require(:memo).permit(:text)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_group

  def index
  end

  def new
    @price = Price.new
  end

  def create
    @price = @group.prices.new(price_params)
    if @price.save
      redirect_to new_group_price_path, notice: "登録しました"
    else
      @prices = @group.prices
      flash.now[:alert] = "入力されていない箇所があります"
      render :new
    end
  end

  def edit
    @price = Price.find(params[:id])
  end

  def update
    @price = Price.find(params[:id])
    if @price.update(price_params)
      redirect_to new_group_price_path, notice: "最安値を編集しました"
    else
      flash.now[:alert] = "入力されていない箇所があります"
      render :edit
    end
  end

  def destroy
    @price = Price.find(params[:id])
    if @price.destroy
      redirect_to new_group_price_path, notice: "削除しました"
    else
      flash.now[:alert] = "通信エラーです"
      render :index 
    end
  end
  
  private
  def price_params
    params.require(:price).permit(:name, :number)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(5)
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: "変更できました"
    else
      flash.now[:alert] = "入力されていない箇所があります"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.group
  .group__title 
    グループ編集
  = form_with model: @group, local: true do |f|
    .group__box
      .group__display
        .group__font
          = f.label :グループ名
          = f.text_field :name, placeholder: "変更したいグループ名", class: "group__field"
        .group__font
          = f.label :メンバー追加
          %input#search__field.group__field{type: "text", placeholder: "追加したいユーザー名"}
          .search__add
      .group__member
        .group__font グループメンバー
        .search__delete
          %p.member__current= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          - @group.users.each do |user|
            - if current_user.name != user.name
              .member
                .member__current
                  = user.name
                  .member__remove{"data-user-id": user.id, "data-user-name": user.name} 削除
                  %input{name: "group[user_ids][]", type:"hidden", value: user.id}
    .group__flex
      = link_to "削除", group_path(@group.id), method: :delete, class: "group__delete"
      = f.submit "更新", class: "group__submit"
    = link_to "チャット画面に戻る", group_messages_path(@group), class: "group__back"

app/views/groups/index.html.haml
.top
  .left
    .left__box
      -if current_user.image.present?
        .left__url
          = image_tag current_user.image.url, class: "left__image"
      -else
        .left__url
          %i.fas.fa-user
    .left__name
      = current_user.name.truncate(15)
    = link_to "グループ作成", new_group_path, class:"left__list"
    = link_to "アカウント編集", edit_user_path(current_user), class:"left__list"
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class:"left__list"
  .right
    .right__title トーク
    .right__box
      - current_user.groups.each do |group|
        .right__box__display
          .rigth__box__right
            = link_to group_messages_path(group) do
              .right__box__group= group.name.truncate(20)
              .right__box__member 
                - group.users.each do |user|
                  = user.name
          .rigth__box__left
            = group.show_last_message.truncate(100)


            

app/views/groups/new.html.haml
.group
  .group__title 
    グループ作成
  = form_with model: @group, local: true do |f|
    .group__box
      .group__display
        .group__font
          = f.label :グループ名
          = f.text_field :name, placeholder: "作成したいグループ名", class: "group__field"
        .group__font
          = f.label :メンバー追加
          %input#search__field.group__field{type: "text", placeholder: "追加したいユーザー名"}
          .search__add
      .group__member
        .group__font グループメンバー
        .search__delete
          %p.member__current= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
    = f.submit "作成", class: "group__send"
    = link_to "トップページに戻る", "/", class: "group__back"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Almemory
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    = javascript_include_tag 'application'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
  %body
    = render 'layouts/notifications'
    = yield

app/views/memos/edit.html.haml
= render "render/header"
.memo
  .memo__title
    メモ内容
  = form_with model: [@group, @memo], local: true do |f|
    .memo__box
      = f.text_area :text, row: 10, placeholder: "メモの内容を入力", class: "memo__form"
    = f.submit "更新", class: "memo__button"

app/views/memos/index.html.haml
= render "render/header"
.memo
  .memo__flow
    .memo__title
      メモ一覧
      = link_to "（メモする）", new_group_memo_path, class: "memo__register"
    - @memos.each do |memo|
      .memo__display
        .memo__text
          = memo.text.truncate(40)
        .memo__link
          = link_to "編集", edit_group_memo_path(@group,memo.id), class: "memo__blue"
        .memo__link
          = link_to "削除", group_memo_path(@group,memo.id), method: :delete, class: "memo__red"

app/views/memos/new.html.haml
= render "render/header"
.memo
  .memo__title
    メモ内容
  = form_with model: [@group, @memo], local: true do |f|
    .memo__box
      = f.text_area :text, row: 10, placeholder: "メモの内容を入力", class: "memo__form"
    = f.submit "保存", class: "memo__button"

app/views/messages/_message.html.haml
.MessageId{data: {message: {id: message.id}}}
  .body__flex
    .left__box
      -if message.user.image.present?
        .left__url
          = image_tag message.user.image.url, class: "left__image"
      -else
        .left__url
          %i.fas.fa-user
    .body__main
      .body__chat
        .body__name
          = message.user.name
        .body__date
          = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
      .body__message
        - if message.content.present?
          .body__text
            = message.content
        - if message.image.present?
          .body__picture
            = image_tag message.image.url

app/views/messages/index.html.haml
= javascript_include_tag "autoUpdating"
= render "render/header"
.body
  .body__contents
    = render @messages
.footer
  = form_with model: [@group, @message], class: "form", local: true do |f|
    .form__placement
      = f.text_field :content, class: "form__message", placeholder: "メッセージを入力"
      = f.label :image, class: "form__image" do
        = icon("fas", "camera")
        = f.file_field :image, class: "form__image--none"
    = f.submit "送信", class: "form__submit"
  = link_to "編集", edit_group_path(@group), class:"group__edit"

app/views/prices/edit.html.haml
= render "render/header"

.price
  .price__title 
    最安値登録
  .price__box
    .price__center
      = form_with model: [@group, @price], local: true do |f|
        .price__name
          = f.label :品名
        .price__text
          = f.text_field :name, placeholder: "登録したい品名", class: "price__field"
        .price__name
          = f.label :値段（税込み）
        .price__text
          = f.text_field :number, placeholder: "半角英数字", class: "price__field"
          %span 円
        = f.submit "更新", class: "price__button"
  .memo__link
    = link_to "削除", group_price_path(@group.id, @price.id), method: :delete, class: "price__red"


        

app/views/prices/index.html.haml
.header
  .button
    %ul.button__right
      %li= link_to "TOP", root_path, class:"button__top"
      %li= link_to @group.name, group_messages_path(@group), class:"button__group"
    .button__left
      = link_to group_prices_path, class:"button__icon" do
        = icon("fas", "calculator")
      = link_to group_memos_path, class:"button__icon" do
        = icon("fas", "book-open")
      = link_to "https://recipe.rakuten.co.jp/", class:"button__icon rakuten" do
        = icon("fas", "cookie")
      = link_to new_group_price_path, class:"button__icon" do
        = icon("fas", "shopping-bag")
.calculation
  .calculation__title
    お手軽計算
  .calculation__box
    .calculation__text
      税金8%
      %form{oninput: "op1.value = Number(a.value) * 1.08;"}
        %input{name: "a", type: "number", placeholder: "金額を入力", class: "calculation__field"}
        × 1.08 ＝
        %output{name: "op1"} 0
    .calculation__text
      税金10%
      %form{oninput: "op2.value = Number(b.value) * 1.1;"}
        %input{name: "b", type: "number", placeholder: "金額を入力", class: "calculation__field"}
        × 1.10 ＝
        %output{name: "op2"} 0
    .calculation__text
      ◯◯あたりの値段
      %br
      例)1個32円の玉ねぎ50個分の値段 
      %b 32×50=1600
      %form{oninput: "op5.value = Number(g.value) * Number(h.value);"}
        %input{name: "g", type: "number", placeholder: "金額を入力", class: "calculation__field"}
        ×
        %input{name: "h", type: "number", placeholder: "数(個数、g)を入力", class: "calculation__field"}
        ＝
        %output{name: "op5"} 0
    .calculation__text
      1あたりの値段
      %form{oninput: "op3.value = Number(c.value) / Number(d.value);"}
        %input{name: "c", type: "number", placeholder: "金額を入力", class: "calculation__field"}
        ÷
        %input{name: "d", type: "number", placeholder: "数(個数、g)を入力", class: "calculation__field"}
        ＝
        %output{name: "op3"} 0
    .calculation__text
      100あたりの値段
      %form{oninput: "op4.value = Number(e.value) / Number(f.value) * 100;"}
        %input{name: "e", type: "number", placeholder: "金額を入力", class: "calculation__field"}
        ÷
        %input{name: "f", type: "number", placeholder: "数(個数、g)を入力", class: "calculation__field"}
        × 100 ＝
        %output{name: "op4"} 0
  

app/views/prices/new.html.haml
= render "render/header"

.price
  .price__title 
    最安値登録
  .price__flex
    .price__display
      .price__flex
        .price__form
          = form_with model: [@group, @price], local: true do |f|
            .price__name
              = f.label :品名
            .price__text
              = f.text_field :name, placeholder: "登録したい品名", class: "price__field"
            .price__name
              = f.label :値段（税込み）
            .price__text
              = f.text_field :number, placeholder: "半角英数字", class: "price__field"
              %span 円
            = f.submit "登録", class: "price__button"
        .search
          .price__name
            最安値検索
          %input.search__field.price__field{placeholder: "検索したい品物", type: "text"}
      .price__explanation
        できるだけ品名は詳細に登録してください。
        %br メーカーや種類ごとに登録しましょう!!
        検索する際、より明確に最安値を検索できます。
        %br
        %br 例）玉ねぎ　→　玉ねぎ1袋3個入り
        例）ハンドソープ　→　◯◯のハンドソープ
    .search__result

app/views/render/_header.html.haml
.header
  .button
    %ul.button__right
      %li= link_to "TOP", root_path, class:"button__top"
      %li= link_to @group.name.truncate(10), group_messages_path(@group), class:"button__group"
    .button__left
      = link_to group_prices_path, class:"button__icon" do
        = icon("fas", "calculator")
      = link_to group_memos_path, class:"button__icon" do
        = icon("fas", "book-open")
      = link_to "https://recipe.rakuten.co.jp/", class:"button__icon rakuten" do
        = icon("fas", "cookie")
      = link_to new_group_price_path, class:"button__icon" do
        = icon("fas", "shopping-bag")

app/views/users/edit.html.haml
.edit
  .edit__title 
    アカウント編集
  = form_for(current_user) do |f|
    .edit__box
      .edit__display
        .edit__font
          = f.label :名前
          = f.text_field :name, autofocus: true, placeholder: "変更したいニックネーム", class: "edit__field"
        .edit__font
          = f.label :email
          = f.email_field :email, placeholder: "変更したメールアドレス", class: "edit__field"
        .edit__font
          = f.label :アイコン
          = f.file_field :image, class: "edit__field"
    = f.submit "更新", class: "edit__send"
  = link_to "トップページに戻る", "/", class: "edit__back"